# Generated by Django 5.2.4 on 2025-07-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('startdate', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
